repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff-check   # linter
        args: [--fix]    # automatycznie poprawia, co się da
      - id: ruff-format  # formatter


  - repo: https://github.com/yunojuno/pre-commit-xenon
    rev: cc59b0431a5d072786b59430e9b342b2881064f6
    hooks:
      - id: xenon
        args: ["--max-absolute=B", "--max-modules=A", "--max-average=A"]

